version: 1.0.{build}
configuration: Release
platform: Any CPU
build:
  project: Medley.sln
  verbosity: minimal
nuget:
  account_feed: true
  project_feed: true
after_build:
- ps: '7z a Binaries.zip C:\projects\medley\Medley.Collections\bin\Release\Medley.Collections.dll'
- ps: '7z a Binaries.zip C:\projects\medley\Medley.Concurrent\bin\Release\Medley.Concurrent.dll'
- ps: '7z a Binaries.zip C:\projects\medley\Medley.Pool\bin\Release\Medley.Pool.dll'
artifacts:
- path: 'Binaries.zip'